MVC_2/Models/CalculatorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_2.Models
{
	public class CalculatorViewModel
	{
		//System.ComponentModel.DataAnnotations ?
		// datatype.custom
		[Required]
		//[RegularExpression("\\d{1,}.\\d{1,}")]
		public double A { get; set; }
		[Required]
		public string Operation { get; set; }
		[Required]
		//[RegularExpression("\\d{1,}.\\d{1,}")]
		public double B { get; set; }
		public string? Result { get; set; }
	}
}

MVC_2/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_2.Services;
using System.ComponentModel.DataAnnotations;
using MVC_2.Models;

namespace MVC_2.Controllers
{
	public class CalculatorController : Controller
	{
		[HttpGet]
		[ActionName("Index")] //зачем action name
		public IActionResult Index()
		{
			CalculatorViewModel model = new CalculatorViewModel();
			return View(model);
		}
		[HttpPost]
		//[ActionName("Calculate")]
		public IActionResult Calculate(CalculatorViewModel model)
		{
			//double a = ;
			//double b;

			//if (!(double.TryParse(InputA, out a) && double.TryParse(InputB, out b))) 

			//if (!ModelState.IsValid) return View();
			if (!ModelState.IsValid) return View("Index", model);

			switch (model.Operation)
			{
				case "+":
					model.Result = (model.A + model.B).ToString();
					break;
				case "-":
					model.Result = (model.A - model.B).ToString();
					break;
				case "*":
					model.Result = (model.A * model.B).ToString();
					break;
				case "/":
					if (model.B == 0)
					{
						ModelState.AddModelError("B", "Деление на ноль невозможно");
						return View("Index", model);
					}
					model.Result = (model.A / model.B).ToString();
					break;
            }

			return View("Index", model);
		}
	}
}

MVC_2/Views/Calculator/Index.cshtml
@using MVC_2.Models

@model CalculatorViewModel


<div class="m-3">
	<h4 class="text-danger">
		@Html.ValidationMessageFor(Model => Model.B)
	</h4>

	<form method="POST" asp-controller="Calculator" asp-action="Calculate">
		<div class="mb-3">
			<label asp-for="@Model.A"></label>
			<input asp-for="@Model.A" /><br />
			<span asp-validation-for="@Model.A"></span>
		</div>

		<div class="mb-3">
			<input type="radio" asp-for="@Model.Operation" value="+" checked>
			<label asp-for="@Model.Operation">+</label>
			<input type="radio" asp-for="@Model.Operation" value="-">
			<label asp-for="@Model.Operation">-</label>
			<input type="radio" asp-for="@Model.Operation" value="*">
			<label asp-for="@Model.Operation">*</label>
			<input type="radio" asp-for="@Model.Operation" value="/">
			<label asp-for="@Model.Operation">/</label>
		</div>

		<div class="mb-3">
			<label asp-for="@Model.B"></label>
			<input asp-for="@Model.B" />
			<span asp-validation-for="@Model.B"></span>
		</div>

		<button type="submit">Посчитать</button>
	</form>
</div>

@if(Model.Result != null) 
{
	<p>@Model.Result</p>
}

MVC_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <script href="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>